import { AreaChart as AreaIcon, Download } from "lucide-react";
import { CartesianGrid, Legend, Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";

import { EmptyState } from "../components/EmptyState.tsx";
import { PageHeader } from "../components/PageHeader.tsx";
import type { ExtrapolationResult } from "../types/hydrodynamics.ts";
import { downloadChartPngs } from "../utils/charts.ts";

interface ChartsPageProps { results: readonly ExtrapolationResult[]; }

function ChartCard({ title, xKey, yLabel, data, firstKey, secondKey, firstLabel, secondLabel }: { title: string; xKey: string; yLabel: string; data: Array<Record<string, number>>; firstKey: string; secondKey: string; firstLabel: string; secondLabel: string }) {
  return <article className="panel chart-card"><div className="chart-heading"><h2>{title}</h2><span>{yLabel}</span></div><div className="chart-canvas"><ResponsiveContainer width="100%" height="100%"><LineChart data={data} margin={{ top: 12, right: 10, bottom: 0, left: 0 }}><CartesianGrid stroke="#d7e3e8" strokeDasharray="3 5" /><XAxis dataKey={xKey} tickLine={false} axisLine={false} fontSize={12} /><YAxis tickLine={false} axisLine={false} fontSize={12} width={54} /><Tooltip contentStyle={{ borderRadius: 10, border: "1px solid #d7e3e8", fontSize: 13 }} /><Legend wrapperStyle={{ fontSize: 12 }} /><Line type="monotone" dataKey={firstKey} name={firstLabel} stroke="#0e7490" strokeWidth={2.4} dot={{ r: 3 }} activeDot={{ r: 5 }} /><Line type="monotone" dataKey={secondKey} name={secondLabel} stroke="#f59e0b" strokeWidth={2.4} dot={{ r: 3 }} activeDot={{ r: 5 }} /></LineChart></ResponsiveContainer></div></article>;
}

export function ChartsPage({ results }: ChartsPageProps) {
  if (!results.length) return <><PageHeader eyebrow="Análise gráfica" title="Curvas de desempenho" description="As séries conectam exclusivamente os pontos experimentais fornecidos e calculados." /><EmptyState icon={AreaIcon} title="Sem pontos para traçar" description="Inclua medições experimentais válidas para gerar as curvas de resistência e potência." /></>;
  const data = results.map((result) => ({ Vp: result.Vp, Fr: result.Fr, "Froude · RT": result.resistanceFroudeKN, "Hughes · RT": result.resistanceHughesKN, "Froude · PE": result.powerFroudeKW, "Hughes · PE": result.powerHughesKW, Ct: result.CtModel, Cf: result.CfModel, Cr: result.CrModel, Cw: result.CwModel }));
  return <><PageHeader eyebrow="Análise gráfica" title="Curvas de desempenho" description="Resistência em kN e potência efetiva em kW para os dois métodos de extrapolação." actions={<button className="button secondary" onClick={() => void downloadChartPngs()}><Download size={16} /> Exportar PNG</button>} /><section className="chart-grid"><ChartCard title="Resistência × velocidade" xKey="Vp" yLabel="RT · kN" data={data} firstKey="Froude · RT" secondKey="Hughes · RT" firstLabel="Froude" secondLabel="Hughes" /><ChartCard title="Potência × velocidade" xKey="Vp" yLabel="PE · kW" data={data} firstKey="Froude · PE" secondKey="Hughes · PE" firstLabel="Froude" secondLabel="Hughes" /><ChartCard title="Resistência × Froude" xKey="Fr" yLabel="RT · kN" data={data} firstKey="Froude · RT" secondKey="Hughes · RT" firstLabel="Froude" secondLabel="Hughes" /><ChartCard title="Potência × Froude" xKey="Fr" yLabel="PE · kW" data={data} firstKey="Froude · PE" secondKey="Hughes · PE" firstLabel="Froude" secondLabel="Hughes" /></section><section className="panel chart-card coefficient-chart"><div className="chart-heading"><h2>Coeficientes hidrodinâmicos × Froude</h2><span>adimensional</span></div><div className="chart-canvas"><ResponsiveContainer width="100%" height="100%"><LineChart data={data}><CartesianGrid stroke="#d7e3e8" strokeDasharray="3 5" /><XAxis dataKey="Fr" tickLine={false} axisLine={false} fontSize={12} /><YAxis tickLine={false} axisLine={false} fontSize={12} width={54} /><Tooltip contentStyle={{ borderRadius: 10, border: "1px solid #d7e3e8", fontSize: 13 }} /><Legend wrapperStyle={{ fontSize: 12 }} /><Line type="monotone" dataKey="Ct" name="Ctₘ" stroke="#164e63" strokeWidth={2.2} /><Line type="monotone" dataKey="Cf" name="Cfₘ" stroke="#0e7490" strokeWidth={2.2} /><Line type="monotone" dataKey="Cr" name="Crₘ" stroke="#f59e0b" strokeWidth={2.2} /><Line type="monotone" dataKey="Cw" name="Cwₘ" stroke="#7c3aed" strokeWidth={2.2} /></LineChart></ResponsiveContainer></div></section></>;
}
